// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-gorm-server/db"
	"wire-gorm-server/handler"
	"wire-gorm-server/repository"
	"wire-gorm-server/service"
)

// Injectors from wire.go:

func InitUserHandler() *handler.UserHandler {
	gormDB := db.ConnectGORM()
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
